export const COMBOS = [
  {
    id: 'C01',
    nome: 'Combo Família Feliz',
    desc: 'Básicos da semana pra toda a família 🏡',
    itens: ['Leite, pão, café, sabonete, papel higiênico'],
    precoOriginal: 32.80,
    preco: 27.90,
    economia: 4.90,
    emoji: '👨‍👩‍👧',
    cor: '#2D5A3D',
    corTexto: '#fff',
    publico: 'familia',
  },
  {
    id: 'C02',
    nome: 'Kit Sexta da Carmen',
    desc: 'Cervejas + salgadinho + gelo pra arrasar na sexta 🍺',
    itens: ['6× Heineken', 'Ruffles', 'Gelo 1kg'],
    precoOriginal: 28.30,
    preco: 22.90,
    economia: 5.40,
    emoji: '🍺',
    cor: '#E8622A',
    corTexto: '#fff',
    publico: 'solteiro',
  },
  {
    id: 'C03',
    nome: 'Adega Express',
    desc: 'Pack com desconto progressivo automático ⚡',
    itens: ['Heineken Pack 6', 'Monster Energy', 'Red Bull'],
    precoOriginal: 45.70,
    preco: 38.90,
    economia: 6.80,
    emoji: '⚡',
    cor: '#C8922A',
    corTexto: '#fff',
    publico: 'solteiro',
  },
  {
    id: 'C04',
    nome: 'Cesta Semana',
    desc: 'Frutas, laticínios e básicos frescos pra semana inteira 🧺',
    itens: ['Água mineral', 'Suco caixinha', 'Absorvente', 'Sabonete'],
    precoOriginal: 25.40,
    preco: 21.90,
    economia: 3.50,
    emoji: '🧺',
    cor: '#1E3D2A',
    corTexto: '#F0E8D8',
    publico: 'familia',
  },
]
